name: Build

on:
  workflow_dispatch:

jobs:
  init:
    runs-on: ubuntu-latest
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: check version
        run: |
          echo node --version
          echo python3 -V
      - name: npm install
        run: npm install
